# -*- coding: utf-8 -*-
"""Rótulos-referência (Opus) dos headers pelados/artefatos, por HEADER EXATO,
julgados pela fala de exemplo + nome + empresas. m=manager a=analyst."""
OV = {
    "Jeffrey Boyd": "manager", "Liam K. Griffin": "manager", "Matt Nicknam": "analyst",
    "'": "manager", "Bill Green": "manager", "James Moylan": "manager",
    "James Cannon": "analyst", "Andrew Baglino": "manager", "Stuart Davis": "manager",
    "Andy Blanchard": "manager", "Jack McHale": "manager", "Rob Binns": "manager",
    "Cherryl Valenzuela": "manager", "Karl D. Triebes": "manager", "Jon Olson": "manager",
    "Marie Myers": "manager", "Ajaypal S. Banga": "manager", "Stewart Stecker": "manager",
    "MichaelTurits": "analyst", "etcom,": "manager", "Chris Danely - JPMorgan": "analyst",
    "Brendan Tansill": "manager", "Sameer Kalucha - JPMorgan": "analyst", "Ken Bruce": "analyst",
    "Brian Milham": "manager", "Brittany Smith": "manager", "Joseph Lima Cardoso": "analyst",
    "Bernard Kim": "manager", "Nigel Coe": "analyst", "Jeff Kvaal": "manager",
    "Donald W. Palette": "manager", "Collister Johnson - Activision Blizzard, Inc.": "manager",
    "Annette N. Arribas - ANSYS, Inc.": "manager", "Bob Lawson": "manager",
    "David Hyman": "manager", "Ernie Maddock": "manager", "Craig Maurer": "analyst",
    "James Flaws": "manager", "PaulSaleh": "manager", "R. Neil Williams": "manager",
    "Simona Jankowski": "manager", "Nicole Noutsios": "manager", "Jaimin Soni": "analyst",
    "Tony Maslowski": "manager", "Greg Jackson": "analyst", "Karl Slatoff": "manager",
    "Don Palette": "manager", "David Joseph": "analyst", "Nabil Elsheshai": "analyst",
    "Spencer Rascoff": "manager", "Timothy Arcuri - Citigroup": "analyst",
    "Jonathan Raviv": "analyst", "Jason Buncovar": "analyst", "Lisa – JPMorgan": "analyst",
    "Steve Milunovich": "analyst", "Karen McLoughlin": "manager", "H. Moore": "manager",
    "Alex Rogers": "manager", "Susan Main": "manager", "Mike McConnell": "analyst",
    "Zack Moxcey - Roper Technologies, Inc.": "manager", "Alax Wang": "manager",
    "DavidGrossman": "analyst", "Tal LIani": "analyst", "Jared Levine": "analyst",
    "Safra Ada Catz": "manager", "Ashwin Shirvaikar – Citigroup": "analyst",
    "Tom McInerney": "manager", "William Kirwan": "analyst", "Robert Kostich": "manager",
    "Mike Sadler": "manager", "George O’Leary": "analyst", "Gregory Q. Brown": "manager",
    "Kyle Mcnealy": "analyst", "Byron Jeffers": "manager", "Alfred Kelly": "manager",
    "Dara Khosrowshahi - Expedia, Inc.": "manager", "Nate Cunningham": "analyst",
    "Dushyant Sharma": "manager", "Bret Taylor": "manager", "Jason Kary": "manager",
    "Graham Vivian Smith": "manager", "Mary Vegh": "manager", "Ajei Gopal": "manager",
    "LeeKrawl": "analyst", "Ryan Griffin": "analyst", "Katie Royce": "manager",
    "Rob D. Owens": "analyst", "Thomas Hirsch": "manager", "David Macgregor": "analyst",
    "Richk Wallace": "manager", "Steven Buhaly": "manager", "Ryan Fitzgerald": "analyst",
    "Bill Ready": "manager", "Steven Milunovich": "analyst", "Paul Seamon": "manager",
    "Ken Gawrelski": "analyst", "Marvin Sims": "manager", "Shannon O'Callaghan": "analyst",
    "Mike Jenneweave - Citigroup": "analyst", "Ned Hooper": "manager",
    "Thomas Georgans": "manager", "Mark Hurd": "manager", "JimSuva": "analyst",
    "Ronald F. Clarke": "manager", "Francois-Xavier Bouvignies": "analyst",
    "Luca Maestri": "manager", "Mark Mondello": "manager", "We grow and create value in 3 ways": "manager",
    "Steven Freitas": "analyst", "Thomas Sweet": "manager", "Jeffrey Huber": "manager",
    "Christopher Reidy": "manager", "Donald J. Rosenberg": "manager", "Yeuk-Fai Mok": "analyst",
    "Colleen Healy": "manager", "Joe Ritchie": "analyst", "Bob Blair": "manager",
    "Sean Kennedy": "analyst", "Paul Mansky- Citigroup": "analyst", "Wilmot Hastings": "manager",
    "Mike Magaro": "manager", "D. James Bidzos": "manager", "-Mark Miller": "analyst",
    "Ryan McInerney": "manager", "Darryl McDonald": "manager", "Sawyer Rice": "analyst",
    "Richard K. Templeton": "manager", "Doug Campbell": "analyst", "Bill Foley": "manager",
    "Sumit Sadana": "manager",
}
